---
name: Container CI

on:
  push:
    branches:
      - master
      - v*
  pull_request:
    branches:
      - master
      - v*
  schedule:
    - cron: '17 14 * * 2'
  workflow_dispatch:

jobs:
  reusable-workflow:
    name: Reusable workflow
    uses: hspaans/.github/.github/workflows/container-ci.yml@master
